### ISSUE TITLE
Error using ClickHouseContainer

### ISSUE THREAD

**Issue by martsv** [testcontainers/testcontainers-scala#111]
I got the following error using ClickHouseContainer.
```
Exception encountered when invoking run on a nested suite.
java.lang.UnsupportedOperationException
	at org.testcontainers.containers.JdbcDatabaseContainer.withPassword(JdbcDatabaseContainer.java:80)
	at com.dimafeng.testcontainers.ClickHouseContainer.<init>(ClickHouseContainer.scala:12)
	at com.dimafeng.testcontainers.ClickHouseContainer$Def.createContainer(ClickHouseContainer.scala:34)
	at com.dimafeng.testcontainers.ClickHouseContainer$Def.createContainer(ClickHouseContainer.scala:24)
	at com.dimafeng.testcontainers.ContainerDef.start(ContainerDef.scala:13)
	at com.dimafeng.testcontainers.ContainerDef.start$(ContainerDef.scala:12)
	at com.dimafeng.testcontainers.ClickHouseContainer$Def.start(ClickHouseContainer.scala:24)
	at com.dimafeng.testcontainers.scalatest.TestContainerForAll.startContainers(TestContainerForAll.scala:31)
	at com.dimafeng.testcontainers.scalatest.TestContainerForAll.startContainers$(TestContainerForAll.scala:30)
	at ClickHouseSpec.startContainers(ClickHouseSpec.scala:5)
	at ClickHouseSpec.startContainers(ClickHouseSpec.scala:5)
	at com.dimafeng.testcontainers.scalatest.TestContainersForAll.run(TestContainersForAll.scala:39)
	at com.dimafeng.testcontainers.scalatest.TestContainersForAll.run$(TestContainersForAll.scala:35)
	at ClickHouseSpec.run(ClickHouseSpec.scala:5)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1349)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1343)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1343)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1033)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1011)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1509)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1011)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:133)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:27)
```
Test spec to reproduce error.
```
import com.dimafeng.testcontainers.ClickHouseContainer
import com.dimafeng.testcontainers.scalatest.TestContainerForAll
import org.scalatest.FlatSpec

class ClickHouseSpec extends FlatSpec with TestContainerForAll {

  override val containerDef = ClickHouseContainer.Def()

  it should "test" in withContainers { clickHouseContainer =>
    assert(clickHouseContainer.containerIpAddress.nonEmpty)
  }
}
```
Versions used.
```
scalaVersion := "2.13.1"

libraryDependencies += "org.scalatest"  %% "scalatest"            % "3.0.8"  % "test"
libraryDependencies += "com.dimafeng"   %% "testcontainers-scala" % "0.35.2" % "test"
libraryDependencies += "com.dimafeng"   %% "testcontainers-scala-clickhouse" % "0.35.2" % "test"
```

**Comment by LMnet** [comment]
@martsv thanks for the report! Fixed here: #112
