### ISSUE TITLE
ClassCastException while constructing PostgreSQL container with new API

### ISSUE THREAD

**Issue by dope9967** [testcontainers/testcontainers-scala#127]
I'm trying to use PostgreSQL container with new API with testcontainers-scala `0.38.0` and I'm getting a `ClassCastException`:
```
An exception or error caused a run to abort: org.testcontainers.containers.PostgreSQLContainer cannot be cast to scala.runtime.Nothing$ 
java.lang.ClassCastException: org.testcontainers.containers.PostgreSQLContainer cannot be cast to scala.runtime.Nothing$
	at com.dimafeng.testcontainers.PostgreSQLContainer.$anonfun$container$1(PostgreSQLContainer.scala:23)
	at scala.Option.map(Option.scala:242)
	at com.dimafeng.testcontainers.PostgreSQLContainer.<init>(PostgreSQLContainer.scala:23)
	at com.dimafeng.testcontainers.PostgreSQLContainer$Def.createContainer(PostgreSQLContainer.scala:90)
```
Following code is enough to replicate.
```
PostgreSQLContainer
      .Def()
      .createContainer()
```
Same code on `0.37.0` seems to work fine.

**Comment by LMnet** [comment]
@dope9967 thanks for your report. I have reproduced the error and found a root cause. Fix will be available soon.

**Comment by dimafeng** [comment]
0.38.1 has been released
