### ISSUE TITLE
Can't pull Mockserver image

### ISSUE THREAD

**Issue by sergeda** [testcontainers/testcontainers-scala#172]
When I'm trying to run my test I'm getting 
`Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=jamesdbloom/mockserver:mockserver-mockserver-5.5.4, imagePullPolicy=DefaultPullPolicy())
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1286)
	at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:615)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:320)
	... 34 more
Caused by: com.github.dockerjava.api.exception.NotFoundException: Status 404: {"message":"manifest for jamesdbloom/mockserver:mockserver-mockserver-5.5.4 not found: manifest unknown: manifest unknown"}
`
I'm using "0.39.3" version of testcontainers

**Comment by dimafeng** [comment]
@sergeda 
Can you try to run `docker pull jamesdbloom/mockserver:mockserver-mockserver-5.5.4` in your terminal? Your issue looks like not related to testcontainers-scala.

**Comment by sergeda** [comment]
@dimafeng That command returns the same error. But if I change `testcontainers-scala-mockserver` version to "0.38.3" it works fine, just container too old. Is it possible to specify what version of container you want to use?

**Comment by dimafeng** [comment]
I think your old version is just cached on your local machine. I'd suggest to fix the docker pull issue in your system.
