### ISSUE TITLE
Testcontainers Dependency missing Jackson Annotations

### ISSUE THREAD

**Issue by jsurls** [testcontainers/testcontainers-scala#174]
I've opened this Issue on the testcontainers-java repo:
https://github.com/testcontainers/testcontainers-java/issues/3972

In that repo, the current version of ```org.testcontainers:testcontainers:jar:1.15.2:test``` is missing the Jackson Annotations dependency. This impacts this repo testcontainers-scala for versions ```0.38.6+```

When running a test locally I get:
```
java.lang.NoSuchMethodError: com.fasterxml.jackson.annotation.JsonFormat$Value.empty()Lcom/fasterxml/jackson/annotation/JsonFormat$Value;
  at org.testcontainers.shaded.com.fasterxml.jackson.databind.cfg.MapperConfig.<clinit>(MapperConfig.java:49)
  at org.testcontainers.shaded.com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:558)
  at org.testcontainers.shaded.com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:474)
```

As a workaround I have to rollback to ```0.38.5``` which points to an older version of testcontainers-java, notably ```1.14.3```

I'm opening this issue to track the action of updating the testcontainers-java dependency after it is resolved in the upstream repository.

**Comment by jsurls** [comment]
Jackson Annotations was omitted intentionally discussed in testcontainers/testcontainers-java#3972

Closing this ticket as no action is forthcoming.
