### ISSUE TITLE
Container failed to start on GHA

### ISSUE THREAD

**Issue by Tochemey** [testcontainers/testcontainers-scala#241]
Hello, my test containers have been working all this while and all of sudden I am seeing the following error:
```
        +test-local *failed* | [info]   org.testcontainers.containers.ContainerLaunchException: Container startup failed
         +test-local *failed* | [info]   at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)
         +test-local *failed* | [info]   at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
         +test-local *failed* | [info]   at org.testcontainers.utility.RyukResourceReaper.maybeStart(RyukResourceReaper.java:78)
         +test-local *failed* | [info]   at org.testcontainers.utility.RyukResourceReaper.init(RyukResourceReaper.java:42)
         +test-local *failed* | [info]   at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:209)
         +test-local *failed* | [info]   at org.testcontainers.DockerClientFactory$1.getDockerClient(DockerClientFactory.java:89)
         +test-local *failed* | [info]   at com.github.dockerjava.api.DockerClientDelegate.authConfig(DockerClientDelegate.java:108)
         +test-local *failed* | [info]   at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:321)
         +test-local *failed* | [info]   at com.dimafeng.testcontainers.SingleContainer.start(Container.scala:47)
         +test-local *failed* | [info]   at com.dimafeng.testcontainers.ForAllTestContainer.run(ForAllTestContainer.scala:17)
         +test-local *failed* | [info]   at com.dimafeng.testcontainers.ForAllTestContainer.run$(ForAllTestContainer.scala:13)
         +test-local *failed* | [info]   at com.github.chiefofstate.MigrationRunnerSpec.run(MigrationRunnerSpec.scala:27)
         +test-local *failed* | [info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:321)
         +test-local *failed* | [info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:517)
         +test-local *failed* | [info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
         +test-local *failed* | [info]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
         +test-local *failed* | [info]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
         +test-local *failed* | [info]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
         +test-local *failed* | [info]   at java.base/java.lang.Thread.run(Thread.java:834)
         +test-local *failed* | [info]   Cause: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
         +test-local *failed* | [info]   at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
         +test-local *failed* | [info]   at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
         +test-local *failed* | [info]   at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
         +test-local *failed* | [info]   at org.testcontainers.utility.RyukResourceReaper.maybeStart(RyukResourceReaper.java:78)
         +test-local *failed* | [info]   at org.testcontainers.utility.RyukResourceReaper.init(RyukResourceReaper.java:42)
         +test-local *failed* | [info]   at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:209)
         +test-local *failed* | [info]   at org.testcontainers.DockerClientFactory$1.getDockerClient(DockerClientFactory.java:89)
         +test-local *failed* | [info]   at com.github.dockerjava.api.DockerClientDelegate.authConfig(DockerClientDelegate.java:108)
         +test-local *failed* | [info]   at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:321)
         +test-local *failed* | [info]   at com.dimafeng.testcontainers.SingleContainer.start(Container.scala:47)
         +test-local *failed* | [info]   at com.dimafeng.testcontainers.ForAllTestContainer.run(ForAllTestContainer.scala:17)
         +test-local *failed* | [info]   at com.dimafeng.testcontainers.ForAllTestContainer.run$(ForAllTestContainer.scala:13)
         +test-local *failed* | [info]   at com.github.chiefofstate.MigrationRunnerSpec.run(MigrationRunnerSpec.scala:27)
         +test-local *failed* | [info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:321)
         +test-local *failed* | [info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:517)
         +test-local *failed* | [info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
         +test-local *failed* | [info]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
         +test-local *failed* | [info]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
         +test-local *failed* | [info]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
         +test-local *failed* | [info]   at java.base/java.lang.Thread.run(Thread.java:834)
         +test-local *failed* | [info]   Cause: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
         +test-local *failed* | [info]   at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:542)
         +test-local *failed* | [info]   at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
         +test-local *failed* | [info]   at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
         +test-local *failed* | [info]   at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
         +test-local *failed* | [info]   at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
         +test-local *failed* | [info]   at org.testcontainers.utility.RyukResourceReaper.maybeStart(RyukResourceReaper.java:78)
         +test-local *failed* | [info]   at org.testcontainers.utility.RyukResourceReaper.init(RyukResourceReaper.java:42)
         +test-local *failed* | [info]   at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:209)
         +test-local *failed* | [info]   at org.testcontainers.DockerClientFactory$1.getDockerClient(DockerClientFactory.java:89)
         +test-local *failed* | [info]   at com.github.dockerjava.api.DockerClientDelegate.authConfig(DockerClientDelegate.java:108)
         +test-local *failed* | [info]   at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:321)
         +test-local *failed* | [info]   at com.dimafeng.testcontainers.SingleContainer.start(Container.scala:47)
         +test-local *failed* | [info]   at com.dimafeng.testcontainers.ForAllTestContainer.run(ForAllTestContainer.scala:17)
         +test-local *failed* | [info]   at com.dimafeng.testcontainers.ForAllTestContainer.run$(ForAllTestContainer.scala:13)
         +test-local *failed* | [info]   at com.github.chiefofstate.MigrationRunnerSpec.run(MigrationRunnerSpec.scala:27)
         +test-local *failed* | [info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:321)
         +test-local *failed* | [info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:517)
         +test-local *failed* | [info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
         +test-local *failed* | [info]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
         +test-local *failed* | [info]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
         +test-local *failed* | [info]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
         +test-local *failed* | [info]   at java.base/java.lang.Thread.run(Thread.java:834)
         +test-local *failed* | [info]   Cause: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"cgroups: cgroup mountpoint does not exist: unknown"}
         +test-local *failed* | [info]   at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
         +test-local *failed* | [info]   at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:102)
         +test-local *failed* | [info]   at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31)
         +test-local *failed* | [info]   at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
         +test-local *failed* | [info]   at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
         +test-local *failed* | [info]   at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
         +test-local *failed* | [info]   at org.testcontainers.shaded.com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43)
         +test-local *failed* | [info]   at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:441)
         +test-local *failed* | [info]   at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
         +test-local *failed* | [info]   at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
         +test-local *failed* | [info]   at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
         +test-local *failed* | [info]   at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
         +test-local *failed* | [info]   at org.testcontainers.utility.RyukResourceReaper.maybeStart(RyukResourceReaper.java:78)
         +test-local *failed* | [info]   at org.testcontainers.utility.RyukResourceReaper.init(RyukResourceReaper.java:42)
         +test-local *failed* | [info]   at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:209)
         +test-local *failed* | [info]   at org.testcontainers.DockerClientFactory$1.getDockerClient(DockerClientFactory.java:89)
         +test-local *failed* | [info]   at com.github.dockerjava.api.DockerClientDelegate.authConfig(DockerClientDelegate.java:108)
         +test-local *failed* | [info]   at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:321)
         +test-local *failed* | [info]   at com.dimafeng.testcontainers.SingleContainer.start(Container.scala:47)
         +test-local *failed* | [info]   at com.dimafeng.testcontainers.ForAllTestContainer.run(ForAllTestContainer.scala:17)
         +test-local *failed* | [info]   at com.dimafeng.testcontainers.ForAllTestContainer.run$(ForAllTestContainer.scala:13)
         +test-local *failed* | [info]   at com.github.chiefofstate.MigrationRunnerSpec.run(MigrationRunnerSpec.scala:27)
         +test-local *failed* | [info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:321)
         +test-local *failed* | [info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:517)
         +test-local *failed* | [info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
         +test-local *failed* | [info]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
         +test-local *failed* | [info]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
         +test-local *failed* | [info]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
         +test-local *failed* | [info]   at java.base/java.lang.Thread.run(Thread.java:834)
   ```

**Comment by Tochemey** [comment]
I can see no one cares about this
