### ISSUE TITLE
Running gradle test on CircleCI

### ISSUE THREAD

**Issue by salam-abdul** [testcontainers/testcontainers-scala#42]
The test containers work perfectly when running locally but seem to have an issue spinning up on CircleCI even with machine level access. Testcontainers is able to determine the docker version and machine status but can't seem to deploy a container. Copying some of the debug log and the CircleCI config. Any assistance is appreciated 😄 

```bash
    2019-02-08 15:50:03,059 0] ERROR: Could not start container
    org.testcontainers.containers.ContainerLaunchException: Timed out waiting for URL to be accessible (http://localhost:32770/ should return HTTP 200)
    	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:197)
    	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
    	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:606)
    	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:292)
    	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:237)
    	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:76)
    	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:235)
    	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:220)
    	at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:738)
    	at org.testcontainers.containers.TestContainerAccessor$.starting(TestContainerAccessor.scala:13)
    	at com.dimafeng.testcontainers.TestContainerProxy$class.starting(TestContainer.scala:106)
    	at com.dimafeng.testcontainers.SingleContainer.starting(TestContainer.scala:111)
    	at com.dimafeng.testcontainers.ForEachTestContainer$class.runTest(TestContainer.scala:26)
```

```yaml
version: 2.0
executorType: machine

jobs:
  build:
    machine: true

    steps:
      # Clone git repository
      - checkout

      # Build Jar
      - run: ./gradlew test
```

**Comment by dimafeng** [comment]
Closing as it can't be reproduced
